In [3]:
import pandas as pd

In [4]:
df = pd.read_csv("estudiantes - Copy.csv")

In [5]:
df.head()

,student_id,programa,semestre,edad,genero,horas_estudio_semana,horas_sueno_noche,tiempo_desplazamiento_min,medio_transporte,nivel_estres,satisfaccion_academica,dias_ejercicio_semana,horas_sociales_semana,uso_ia_generativa,confianza_programando,area_interes_datos,modalidad_preferida,promedio_acumulado,fecha_encuesta
0,E0001,Economía,5,21,Mujer,16.8,5.5,61.0,Bus,4,4,3,7.2,A veces,3,Ingeniería de datos,Presencial,3.47,2026-08-01
1,E0002,Administración,6,23,Mujer,23.5,7.2,98.0,TransMilenio,4,4,2,10.8,Nunca,2,No estoy seguro,Presencial,3.69,2026-08-10
2,E0003,Administración,1,17,Hombre,12.6,6.7,55.0,TransMilenio,5,4,3,6.8,A veces,4,Analítica de negocio,Presencial,3.26,2026-08-21
3,E0004,Ciencia de Datos,8,21,Mujer,15.7,6.1,57.0,Moto,4,3,1,14.3,Nunca,4,Analítica de negocio,Presencial,2.90,2026-08-19
4,E0005,Diseño,3,22,Mujer,20.5,6.4,50.0,Carro,5,4,5,11.0,A veces,2,No estoy seguro,Presencial,3.54,2026-08-04

In [6]:
df.student_id

0       E0001
1       E0002
2       E0003
3       E0004
4       E0005
        ...
2507    E2113
2508    E0456
2509    E1001
2510    E0438
2511    E1192
Name: student_id, Length: 2512, dtype: str

In [9]:
col = df[["student_id","programa","semestre","edad"]]
col

     student_id                programa  semestre  edad
0         E0001                Economía         5    21
1         E0002          Administración         6    23
2         E0003          Administración         1    17
3         E0004        Ciencia de Datos         8    21
4         E0005                  Diseño         3    22
...         ...                     ...       ...   ...
2507      E2113        Ciencia de Datos         1    18
2508      E0456          Administración         2    19
2509      E1001  Ingeniería de Sistemas         1    19
2510      E0438   Ingeniería Industrial         1    19
2511      E1192          Administración         2    20

[2512 rows x 4 columns]

In [12]:
df.iloc[3]

student_id                                  E0004
programa                         Ciencia de Datos
semestre                                        8
edad                                           21
genero                                      Mujer
horas_estudio_semana                         15.7
horas_sueno_noche                             6.1
tiempo_desplazamiento_min                    57.0
medio_transporte                             Moto
nivel_estres                                    4
satisfaccion_academica                          3
dias_ejercicio_semana                           1
horas_sociales_semana                        14.3
uso_ia_generativa                           Nunca
confianza_programando                           4
area_interes_datos           Analítica de negocio
modalidad_preferida                    Presencial
promedio_acumulado                            2.9
fecha_encuesta                         2026-08-19
Name: 3, dtype: object

In [13]:
df.iloc[3,0]

'E0004'

In [19]:
df.loc[3,"student_id"]

'E0004'

In [20]:
df.isna().sum()

student_id                    0
programa                      0
semestre                      0
edad                          0
genero                        0
horas_estudio_semana          0
horas_sueno_noche            72
tiempo_desplazamiento_min    56
medio_transporte              0
nivel_estres                  0
satisfaccion_academica        0
dias_ejercicio_semana         0
horas_sociales_semana         0
uso_ia_generativa             0
confianza_programando         0
area_interes_datos           41
modalidad_preferida           0
promedio_acumulado            0
fecha_encuesta                0
dtype: int64

In [21]:
df.dropna(subset=["area_interes_datos"])

,student_id,programa,semestre,edad,genero,horas_estudio_semana,horas_sueno_noche,tiempo_desplazamiento_min,medio_transporte,nivel_estres,satisfaccion_academica,dias_ejercicio_semana,horas_sociales_semana,uso_ia_generativa,confianza_programando,area_interes_datos,modalidad_preferida,promedio_acumulado,fecha_encuesta
0,E0001,Economía,5,21,Mujer,16.8,5.5,61.0,Bus,4,4,3,7.2,A veces,3,Ingeniería de datos,Presencial,3.47,2026-08-01
1,E0002,Administración,6,23,Mujer,23.5,7.2,98.0,TransMilenio,4,4,2,10.8,Nunca,2,No estoy seguro,Presencial,3.69,2026-08-10
2,E0003,Administración,1,17,Hombre,12.6,6.7,55.0,TransMilenio,5,4,3,6.8,A veces,4,Analítica de negocio,Presencial,3.26,2026-08-21
3,E0004,Ciencia de Datos,8,21,Mujer,15.7,6.1,57.0,Moto,4,3,1,14.3,Nunca,4,Analítica de negocio,Presencial,2.90,2026-08-19
4,E0005,Diseño,3,22,Mujer,20.5,6.4,50.0,Carro,5,4,5,11.0,A veces,2,No estoy seguro,Presencial,3.54,2026-08-04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2507,E2113,Ciencia de Datos,1,18,Mujer,13.7,6.3,81.0,Caminando,5,4,5,9.7,Frecuentemente,3,Analítica de negocio,Presencial,3.67,2026-08-10
2508,E0456,Administración,2,19,Mujer,17.7,5.8,47.0,Caminando,4,4,3,4.9,Frecuentemente,1,IA y ML,Presencial,3.24,2026-08-04
2509,E1001,Ingeniería de Sistemas,1,19,Mujer,20.1,5.2,92.0,Caminando,5,3,1,9.1,Frecuentemente,4,Analítica de negocio,Presencial,3.82,2026-08-19
2510,E0438,Ingeniería Industrial,1,19,Mujer,15.5,7.8,50.0,TransMilenio,3,4,5,3.7,Todos los días,3,Analítica de negocio,Presencial,3.79,2026-08-11
2511,E1192,Administración,2,20,Mujer,15.6,7.7,50.0,Caminando,3,4,6,10.8,A veces,4,Visualización,Presencial,3.75,2026-08-02

In [22]:
df.drop_duplicates(subset=["programa"],keep="last")

,student_id,programa,semestre,edad,genero,horas_estudio_semana,horas_sueno_noche,tiempo_desplazamiento_min,medio_transporte,nivel_estres,satisfaccion_academica,dias_ejercicio_semana,horas_sociales_semana,uso_ia_generativa,confianza_programando,area_interes_datos,modalidad_preferida,promedio_acumulado,fecha_encuesta
2387,E2388,Ciencia Datos,4,18,Mujer,15.1,7.5,0.0,Carro,4,4,1,2.2,A veces,5,Analítica de negocio,Presencial,3.78,2026-08-10
2501,E1077,Psicología,4,20,Hombre,19.0,6.4,58.0,Carro,4,4,3,7.8,Nunca,3,Ingeniería de datos,Presencial,3.08,2026-08-04
2503,E0135,Diseño,2,20,Mujer,15.2,7.6,38.0,Carro,2,5,1,7.1,A veces,3,Ingeniería de datos,Presencial,3.94,2026-08-13
2506,E2010,Economía,5,19,Hombre,17.2,6.4,26.0,Moto,4,4,2,8.0,A veces,2,IA y ML,Presencial,3.59,2026-08-11
2507,E2113,Ciencia de Datos,1,18,Mujer,13.7,6.3,81.0,Caminando,5,4,5,9.7,Frecuentemente,3,Analítica de negocio,Presencial,3.67,2026-08-10
2509,E1001,Ingeniería de Sistemas,1,19,Mujer,20.1,5.2,92.0,Caminando,5,3,1,9.1,Frecuentemente,4,Analítica de negocio,Presencial,3.82,2026-08-19
2510,E0438,Ingeniería Industrial,1,19,Mujer,15.5,7.8,50.0,TransMilenio,3,4,5,3.7,Todos los días,3,Analítica de negocio,Presencial,3.79,2026-08-11
2511,E1192,Administración,2,20,Mujer,15.6,7.7,50.0,Caminando,3,4,6,10.8,A veces,4,Visualización,Presencial,3.75,2026-08-02

## 2.Filtros

In [26]:
  df[df["nivel_estres"] >= 4]

,student_id,programa,semestre,edad,genero,horas_estudio_semana,horas_sueno_noche,tiempo_desplazamiento_min,medio_transporte,nivel_estres,satisfaccion_academica,dias_ejercicio_semana,horas_sociales_semana,uso_ia_generativa,confianza_programando,area_interes_datos,modalidad_preferida,promedio_acumulado,fecha_encuesta
0,E0001,Economía,5,21,Mujer,16.8,5.5,61.0,Bus,4,4,3,7.2,A veces,3,Ingeniería de datos,Presencial,3.47,2026-08-01
1,E0002,Administración,6,23,Mujer,23.5,7.2,98.0,TransMilenio,4,4,2,10.8,Nunca,2,No estoy seguro,Presencial,3.69,2026-08-10
2,E0003,Administración,1,17,Hombre,12.6,6.7,55.0,TransMilenio,5,4,3,6.8,A veces,4,Analítica de negocio,Presencial,3.26,2026-08-21
3,E0004,Ciencia de Datos,8,21,Mujer,15.7,6.1,57.0,Moto,4,3,1,14.3,Nunca,4,Analítica de negocio,Presencial,2.90,2026-08-19
4,E0005,Diseño,3,22,Mujer,20.5,6.4,50.0,Carro,5,4,5,11.0,A veces,2,No estoy seguro,Presencial,3.54,2026-08-04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2505,E1375,Ciencia de Datos,2,18,Mujer,12.3,7.5,108.0,TransMilenio,5,4,0,6.3,Frecuentemente,3,IA y ML,Presencial,3.02,2026-08-01
2506,E2010,Economía,5,19,Hombre,17.2,6.4,26.0,Moto,4,4,2,8.0,A veces,2,IA y ML,Presencial,3.59,2026-08-11
2507,E2113,Ciencia de Datos,1,18,Mujer,13.7,6.3,81.0,Caminando,5,4,5,9.7,Frecuentemente,3,Analítica de negocio,Presencial,3.67,2026-08-10
2508,E0456,Administración,2,19,Mujer,17.7,5.8,47.0,Caminando,4,4,3,4.9,Frecuentemente,1,IA y ML,Presencial,3.24,2026-08-04
2509,E1001,Ingeniería de Sistemas,1,19,Mujer,20.1,5.2,92.0,Caminando,5,3,1,9.1,Frecuentemente,4,Analítica de negocio,Presencial,3.82,2026-08-19

In [29]:
df[df["programa"] == "Ciencia de Datos"]

,student_id,programa,semestre,edad,genero,horas_estudio_semana,horas_sueno_noche,tiempo_desplazamiento_min,medio_transporte,nivel_estres,satisfaccion_academica,dias_ejercicio_semana,horas_sociales_semana,uso_ia_generativa,confianza_programando,area_interes_datos,modalidad_preferida,promedio_acumulado,fecha_encuesta
3,E0004,Ciencia de Datos,8,21,Mujer,15.7,6.1,57.0,Moto,4,3,1,14.3,Nunca,4,Analítica de negocio,Presencial,2.90,2026-08-19
5,E0006,Ciencia de Datos,4,22,Hombre,23.4,6.0,77.0,Bus,5,4,5,5.7,A veces,5,Ciencia social computacional,Presencial,3.13,2026-08-10
11,E0012,Ciencia de Datos,5,20,Mujer,11.9,8.1,78.0,TransMilenio,3,5,5,2.0,A veces,4,No estoy seguro,Híbrida,3.59,2026-08-10
13,E0014,Ciencia de Datos,4,24,Mujer,20.9,8.0,39.0,Carro,4,4,2,3.8,A veces,3,Analítica de negocio,Presencial,4.14,2026-08-05
23,E0024,Ciencia de Datos,4,22,Mujer,15.2,7.1,37.0,TransMilenio,5,4,3,3.4,Todos los días,2,Analítica de negocio,Presencial,3.19,2026-08-05
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2475,E2476,Ciencia de Datos,5,22,No binario,10.3,6.9,0.0,TransMilenio,3,4,2,12.0,A veces,4,IA y ML,Presencial,3.38,2026-08-15
2476,E2477,Ciencia de Datos,4,22,Hombre,9.3,8.3,40.0,Moto,2,4,0,13.5,Frecuentemente,4,Analítica de negocio,Presencial,3.15,2026-08-02
2500,E1000,Ciencia de Datos,3,22,Mujer,13.6,5.2,78.0,TransMilenio,5,2,3,11.7,A veces,4,Analítica de negocio,Presencial,2.89,2026-08-17
2505,E1375,Ciencia de Datos,2,18,Mujer,12.3,7.5,108.0,TransMilenio,5,4,0,6.3,Frecuentemente,3,IA y ML,Presencial,3.02,2026-08-01
2507,E2113,Ciencia de Datos,1,18,Mujer,13.7,6.3,81.0,Caminando,5,4,5,9.7,Frecuentemente,3,Analítica de negocio,Presencial,3.67,2026-08-10

In [30]:
df[df["semestre"].isin([1,2,3])]

,student_id,programa,semestre,edad,genero,horas_estudio_semana,horas_sueno_noche,tiempo_desplazamiento_min,medio_transporte,nivel_estres,satisfaccion_academica,dias_ejercicio_semana,horas_sociales_semana,uso_ia_generativa,confianza_programando,area_interes_datos,modalidad_preferida,promedio_acumulado,fecha_encuesta
2,E0003,Administración,1,17,Hombre,12.6,6.7,55.0,TransMilenio,5,4,3,6.8,A veces,4,Analítica de negocio,Presencial,3.26,2026-08-21
4,E0005,Diseño,3,22,Mujer,20.5,6.4,50.0,Carro,5,4,5,11.0,A veces,2,No estoy seguro,Presencial,3.54,2026-08-04
6,E0007,Ingeniería de Sistemas,1,20,Hombre,12.6,8.0,79.0,Caminando,5,4,5,6.0,Frecuentemente,3,Visualización,Híbrida,3.44,2026-08-11
10,E0011,Ingeniería Industrial,1,21,Mujer,8.6,5.9,94.0,Caminando,5,4,3,5.7,A veces,2,Visualización,Híbrida,3.72,2026-08-18
14,E0015,Economía,3,22,Hombre,20.8,7.3,145.0,TransMilenio,4,4,4,15.7,Todos los días,2,Analítica de negocio,Presencial,3.86,2026-08-20
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2507,E2113,Ciencia de Datos,1,18,Mujer,13.7,6.3,81.0,Caminando,5,4,5,9.7,Frecuentemente,3,Analítica de negocio,Presencial,3.67,2026-08-10
2508,E0456,Administración,2,19,Mujer,17.7,5.8,47.0,Caminando,4,4,3,4.9,Frecuentemente,1,IA y ML,Presencial,3.24,2026-08-04
2509,E1001,Ingeniería de Sistemas,1,19,Mujer,20.1,5.2,92.0,Caminando,5,3,1,9.1,Frecuentemente,4,Analítica de negocio,Presencial,3.82,2026-08-19
2510,E0438,Ingeniería Industrial,1,19,Mujer,15.5,7.8,50.0,TransMilenio,3,4,5,3.7,Todos los días,3,Analítica de negocio,Presencial,3.79,2026-08-11
2511,E1192,Administración,2,20,Mujer,15.6,7.7,50.0,Caminando,3,4,6,10.8,A veces,4,Visualización,Presencial,3.75,2026-08-02

In [32]:
df.query("horas_sueno_noche >= 4")

,student_id,programa,semestre,edad,genero,horas_estudio_semana,horas_sueno_noche,tiempo_desplazamiento_min,medio_transporte,nivel_estres,satisfaccion_academica,dias_ejercicio_semana,horas_sociales_semana,uso_ia_generativa,confianza_programando,area_interes_datos,modalidad_preferida,promedio_acumulado,fecha_encuesta
0,E0001,Economía,5,21,Mujer,16.8,5.5,61.0,Bus,4,4,3,7.2,A veces,3,Ingeniería de datos,Presencial,3.47,2026-08-01
1,E0002,Administración,6,23,Mujer,23.5,7.2,98.0,TransMilenio,4,4,2,10.8,Nunca,2,No estoy seguro,Presencial,3.69,2026-08-10
2,E0003,Administración,1,17,Hombre,12.6,6.7,55.0,TransMilenio,5,4,3,6.8,A veces,4,Analítica de negocio,Presencial,3.26,2026-08-21
3,E0004,Ciencia de Datos,8,21,Mujer,15.7,6.1,57.0,Moto,4,3,1,14.3,Nunca,4,Analítica de negocio,Presencial,2.90,2026-08-19
4,E0005,Diseño,3,22,Mujer,20.5,6.4,50.0,Carro,5,4,5,11.0,A veces,2,No estoy seguro,Presencial,3.54,2026-08-04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2507,E2113,Ciencia de Datos,1,18,Mujer,13.7,6.3,81.0,Caminando,5,4,5,9.7,Frecuentemente,3,Analítica de negocio,Presencial,3.67,2026-08-10
2508,E0456,Administración,2,19,Mujer,17.7,5.8,47.0,Caminando,4,4,3,4.9,Frecuentemente,1,IA y ML,Presencial,3.24,2026-08-04
2509,E1001,Ingeniería de Sistemas,1,19,Mujer,20.1,5.2,92.0,Caminando,5,3,1,9.1,Frecuentemente,4,Analítica de negocio,Presencial,3.82,2026-08-19
2510,E0438,Ingeniería Industrial,1,19,Mujer,15.5,7.8,50.0,TransMilenio,3,4,5,3.7,Todos los días,3,Analítica de negocio,Presencial,3.79,2026-08-11
2511,E1192,Administración,2,20,Mujer,15.6,7.7,50.0,Caminando,3,4,6,10.8,A veces,4,Visualización,Presencial,3.75,2026-08-02

In [34]:
df[(df["nivel_estres"] >= 4) & (df["horas_sueno_noche"] < 6)]

,student_id,programa,semestre,edad,genero,horas_estudio_semana,horas_sueno_noche,tiempo_desplazamiento_min,medio_transporte,nivel_estres,satisfaccion_academica,dias_ejercicio_semana,horas_sociales_semana,uso_ia_generativa,confianza_programando,area_interes_datos,modalidad_preferida,promedio_acumulado,fecha_encuesta
0,E0001,Economía,5,21,Mujer,16.8,5.5,61.0,Bus,4,4,3,7.2,A veces,3,Ingeniería de datos,Presencial,3.47,2026-08-01
10,E0011,Ingeniería Industrial,1,21,Mujer,8.6,5.9,94.0,Caminando,5,4,3,5.7,A veces,2,Visualización,Híbrida,3.72,2026-08-18
15,E0016,Psicología,1,20,Hombre,6.8,5.0,30.0,TransMilenio,5,3,4,3.6,A veces,2,Analítica de negocio,Presencial,3.32,2026-08-09
16,E0017,Ingeniería de Sistemas,4,25,Mujer,9.5,5.6,76.0,TransMilenio,4,4,2,2.3,Frecuentemente,4,IA y ML,Híbrida,3.20,2026-08-02
25,E0026,Economía,1,19,Hombre,6.7,5.1,34.0,Bicicleta,4,4,2,13.8,Frecuentemente,1,IA y ML,Presencial,3.12,2026-08-10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2489,E2490,Administración,1,20,Hombre,2.5,5.8,36.0,Bus,4,4,6,17.8,A veces,1,Ciencia social computacional,Presencial,2.73,2026-08-06
2499,E2500,Ingeniería Industrial,6,22,Mujer,21.0,5.3,48.0,TransMilenio,4,4,0,8.2,Frecuentemente,2,IA y ML,Presencial,3.18,2026-08-11
2500,E1000,Ciencia de Datos,3,22,Mujer,13.6,5.2,78.0,TransMilenio,5,2,3,11.7,A veces,4,Analítica de negocio,Presencial,2.89,2026-08-17
2508,E0456,Administración,2,19,Mujer,17.7,5.8,47.0,Caminando,4,4,3,4.9,Frecuentemente,1,IA y ML,Presencial,3.24,2026-08-04
2509,E1001,Ingeniería de Sistemas,1,19,Mujer,20.1,5.2,92.0,Caminando,5,3,1,9.1,Frecuentemente,4,Analítica de negocio,Presencial,3.82,2026-08-19

In [38]:
df.query(" nivel_estres >= 4 or horas_sueno_noche < 6")

,student_id,programa,semestre,edad,genero,horas_estudio_semana,horas_sueno_noche,tiempo_desplazamiento_min,medio_transporte,nivel_estres,satisfaccion_academica,dias_ejercicio_semana,horas_sociales_semana,uso_ia_generativa,confianza_programando,area_interes_datos,modalidad_preferida,promedio_acumulado,fecha_encuesta
0,E0001,Economía,5,21,Mujer,16.8,5.5,61.0,Bus,4,4,3,7.2,A veces,3,Ingeniería de datos,Presencial,3.47,2026-08-01
1,E0002,Administración,6,23,Mujer,23.5,7.2,98.0,TransMilenio,4,4,2,10.8,Nunca,2,No estoy seguro,Presencial,3.69,2026-08-10
2,E0003,Administración,1,17,Hombre,12.6,6.7,55.0,TransMilenio,5,4,3,6.8,A veces,4,Analítica de negocio,Presencial,3.26,2026-08-21
3,E0004,Ciencia de Datos,8,21,Mujer,15.7,6.1,57.0,Moto,4,3,1,14.3,Nunca,4,Analítica de negocio,Presencial,2.90,2026-08-19
4,E0005,Diseño,3,22,Mujer,20.5,6.4,50.0,Carro,5,4,5,11.0,A veces,2,No estoy seguro,Presencial,3.54,2026-08-04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2505,E1375,Ciencia de Datos,2,18,Mujer,12.3,7.5,108.0,TransMilenio,5,4,0,6.3,Frecuentemente,3,IA y ML,Presencial,3.02,2026-08-01
2506,E2010,Economía,5,19,Hombre,17.2,6.4,26.0,Moto,4,4,2,8.0,A veces,2,IA y ML,Presencial,3.59,2026-08-11
2507,E2113,Ciencia de Datos,1,18,Mujer,13.7,6.3,81.0,Caminando,5,4,5,9.7,Frecuentemente,3,Analítica de negocio,Presencial,3.67,2026-08-10
2508,E0456,Administración,2,19,Mujer,17.7,5.8,47.0,Caminando,4,4,3,4.9,Frecuentemente,1,IA y ML,Presencial,3.24,2026-08-04
2509,E1001,Ingeniería de Sistemas,1,19,Mujer,20.1,5.2,92.0,Caminando,5,3,1,9.1,Frecuentemente,4,Analítica de negocio,Presencial,3.82,2026-08-19

## Transformaciones

In [45]:
df["fecha_encuesta"] = pd.to_datetime(df["fecha_encuesta"],errors="coerce")
df.dtypes

student_id                              str
programa                                str
semestre                              int64
edad                                  int64
genero                                  str
horas_estudio_semana                float64
horas_sueno_noche                   float64
tiempo_desplazamiento_min           float64
medio_transporte                        str
nivel_estres                          int64
satisfaccion_academica                int64
dias_ejercicio_semana                 int64
horas_sociales_semana               float64
uso_ia_generativa                       str
confianza_programando                 int64
area_interes_datos                      str
modalidad_preferida                     str
promedio_acumulado                  float64
fecha_encuesta               datetime64[us]
dtype: object

In [46]:
df["programa"].value_counts()

programa
Ciencia de Datos          475
Ingeniería Industrial     453
Ingeniería de Sistemas    427
Economía                  383
Administración            362
Diseño                    209
Psicología                200
Ciencia Datos               3
Name: count, dtype: int64

In [48]:
df["programa"] = df["programa"].str.replace("Ciencia Datos", "Ciencia de Datos")

In [49]:
df["programa"].value_counts()

programa
Ciencia de Datos          478
Ingeniería Industrial     453
Ingeniería de Sistemas    427
Economía                  383
Administración            362
Diseño                    209
Psicología                200
Name: count, dtype: int64

In [52]:
df["balance_estudio_sueño"] = df["horas_estudio_semana"] / (df["horas_sueño_noche"])

KeyError: 'horas_sueño_noche'