In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("estudiantes - Copy.csv")
df

,student_id,programa,semestre,edad,genero,horas_estudio_semana,horas_sueno_noche,tiempo_desplazamiento_min,medio_transporte,nivel_estres,satisfaccion_academica,dias_ejercicio_semana,horas_sociales_semana,uso_ia_generativa,confianza_programando,area_interes_datos,modalidad_preferida,promedio_acumulado,fecha_encuesta
0,E0001,Economía,5,21,Mujer,16.8,5.5,61.0,Bus,4,4,3,7.2,A veces,3,Ingeniería de datos,Presencial,3.47,2026-08-01
1,E0002,Administración,6,23,Mujer,23.5,7.2,98.0,TransMilenio,4,4,2,10.8,Nunca,2,No estoy seguro,Presencial,3.69,2026-08-10
2,E0003,Administración,1,17,Hombre,12.6,6.7,55.0,TransMilenio,5,4,3,6.8,A veces,4,Analítica de negocio,Presencial,3.26,2026-08-21
3,E0004,Ciencia de Datos,8,21,Mujer,15.7,6.1,57.0,Moto,4,3,1,14.3,Nunca,4,Analítica de negocio,Presencial,2.90,2026-08-19
4,E0005,Diseño,3,22,Mujer,20.5,6.4,50.0,Carro,5,4,5,11.0,A veces,2,No estoy seguro,Presencial,3.54,2026-08-04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2507,E2113,Ciencia de Datos,1,18,Mujer,13.7,6.3,81.0,Caminando,5,4,5,9.7,Frecuentemente,3,Analítica de negocio,Presencial,3.67,2026-08-10
2508,E0456,Administración,2,19,Mujer,17.7,5.8,47.0,Caminando,4,4,3,4.9,Frecuentemente,1,IA y ML,Presencial,3.24,2026-08-04
2509,E1001,Ingeniería de Sistemas,1,19,Mujer,20.1,5.2,92.0,Caminando,5,3,1,9.1,Frecuentemente,4,Analítica de negocio,Presencial,3.82,2026-08-19
2510,E0438,Ingeniería Industrial,1,19,Mujer,15.5,7.8,50.0,TransMilenio,3,4,5,3.7,Todos los días,3,Analítica de negocio,Presencial,3.79,2026-08-11
2511,E1192,Administración,2,20,Mujer,15.6,7.7,50.0,Caminando,3,4,6,10.8,A veces,4,Visualización,Presencial,3.75,2026-08-02

In [4]:
df.query("nivel_estres <= 4")

,student_id,programa,semestre,edad,genero,horas_estudio_semana,horas_sueno_noche,tiempo_desplazamiento_min,medio_transporte,nivel_estres,satisfaccion_academica,dias_ejercicio_semana,horas_sociales_semana,uso_ia_generativa,confianza_programando,area_interes_datos,modalidad_preferida,promedio_acumulado,fecha_encuesta
0,E0001,Economía,5,21,Mujer,16.8,5.5,61.0,Bus,4,4,3,7.2,A veces,3,Ingeniería de datos,Presencial,3.47,2026-08-01
1,E0002,Administración,6,23,Mujer,23.5,7.2,98.0,TransMilenio,4,4,2,10.8,Nunca,2,No estoy seguro,Presencial,3.69,2026-08-10
3,E0004,Ciencia de Datos,8,21,Mujer,15.7,6.1,57.0,Moto,4,3,1,14.3,Nunca,4,Analítica de negocio,Presencial,2.90,2026-08-19
7,E0008,Ingeniería de Sistemas,4,22,Prefiere no responder,19.8,7.1,33.0,TransMilenio,4,4,2,0.8,Todos los días,3,NaN,Híbrida,3.54,2026-08-06
8,E0009,Ingeniería Industrial,5,20,Mujer,8.9,6.5,59.0,Moto,4,3,1,6.1,A veces,3,Analítica de negocio,Presencial,3.36,2026-08-03
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2504,E1280,Ingeniería de Sistemas,3,19,Mujer,17.6,7.3,73.0,Bicicleta,3,4,4,9.5,A veces,2,No estoy seguro,Presencial,3.67,2026-08-18
2506,E2010,Economía,5,19,Hombre,17.2,6.4,26.0,Moto,4,4,2,8.0,A veces,2,IA y ML,Presencial,3.59,2026-08-11
2508,E0456,Administración,2,19,Mujer,17.7,5.8,47.0,Caminando,4,4,3,4.9,Frecuentemente,1,IA y ML,Presencial,3.24,2026-08-04
2510,E0438,Ingeniería Industrial,1,19,Mujer,15.5,7.8,50.0,TransMilenio,3,4,5,3.7,Todos los días,3,Analítica de negocio,Presencial,3.79,2026-08-11
2511,E1192,Administración,2,20,Mujer,15.6,7.7,50.0,Caminando,3,4,6,10.8,A veces,4,Visualización,Presencial,3.75,2026-08-02

In [8]:
df[~(df["nivel_estres"] >= 4)]

,student_id,programa,semestre,edad,genero,horas_estudio_semana,horas_sueno_noche,tiempo_desplazamiento_min,medio_transporte,nivel_estres,satisfaccion_academica,dias_ejercicio_semana,horas_sociales_semana,uso_ia_generativa,confianza_programando,area_interes_datos,modalidad_preferida,promedio_acumulado,fecha_encuesta
11,E0012,Ciencia de Datos,5,20,Mujer,11.9,8.1,78.0,TransMilenio,3,5,5,2.0,A veces,4,No estoy seguro,Híbrida,3.59,2026-08-10
19,E0020,Administración,4,19,Hombre,17.6,6.9,58.0,TransMilenio,3,5,4,7.8,Frecuentemente,1,Visualización,Híbrida,4.12,2026-08-04
22,E0023,Economía,3,22,Mujer,14.0,7.8,16.0,Bus,3,4,3,0.0,Frecuentemente,3,IA y ML,Presencial,3.15,2026-08-11
27,E0028,Ingeniería de Sistemas,4,22,Hombre,16.6,8.2,0.0,Bus,3,4,2,6.8,A veces,3,Analítica de negocio,Presencial,3.71,2026-08-13
28,E0029,Administración,6,18,Prefiere no responder,6.9,6.4,17.0,TransMilenio,3,3,4,9.8,A veces,3,Analítica de negocio,Presencial,3.54,2026-08-14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2496,E2497,Ingeniería Industrial,2,18,Hombre,15.7,7.6,37.0,TransMilenio,3,5,1,12.1,A veces,2,Ciencia social computacional,Virtual,3.69,2026-08-06
2503,E0135,Diseño,2,20,Mujer,15.2,7.6,38.0,Carro,2,5,1,7.1,A veces,3,Ingeniería de datos,Presencial,3.94,2026-08-13
2504,E1280,Ingeniería de Sistemas,3,19,Mujer,17.6,7.3,73.0,Bicicleta,3,4,4,9.5,A veces,2,No estoy seguro,Presencial,3.67,2026-08-18
2510,E0438,Ingeniería Industrial,1,19,Mujer,15.5,7.8,50.0,TransMilenio,3,4,5,3.7,Todos los días,3,Analítica de negocio,Presencial,3.79,2026-08-11
2511,E1192,Administración,2,20,Mujer,15.6,7.7,50.0,Caminando,3,4,6,10.8,A veces,4,Visualización,Presencial,3.75,2026-08-02